version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "shareit"
      POSTGRES_USER: "shareituser"
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"